import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { after, before, beforeEach, afterEach, test } from "node:test";
import { PGlite } from "@electric-sql/pglite";

const db = new PGlite();
const master = "00000000-0000-0000-0000-000000000001";
const staff = "00000000-0000-0000-0000-000000000002";
const q = async (sql, args = []) => (await db.query(sql, args)).rows;

before(async () => {
  await db.exec(`
    create role anon; create role authenticated;
    create schema auth;
    create table auth.users(id uuid primary key);
    create function auth.uid() returns uuid language sql stable as
      $$ select nullif(current_setting('request.jwt.claim.sub', true), '')::uuid $$;
    create table public.users(id uuid primary key, oss_role text not null);
    insert into auth.users values ('${master}'), ('${staff}');
    insert into public.users values ('${master}', 'master'), ('${staff}', 'staff');

    create table public.after_services(
      id bigint primary key, customer_id bigint, item_name text not null,
      quantity integer not null, service_case_type text not null, status text not null,
      defective_hold_id uuid
    );
    create table public.after_service_outbound_cost_allocations(
      id uuid primary key default gen_random_uuid(), after_service_id bigint not null,
      unit_price integer, outbound_quantity integer not null, received_quantity integer default 0,
      created_at timestamptz not null default now()
    );
    create table public.settlement_expense_categories(
      id uuid primary key default gen_random_uuid(), name text not null unique,
      is_active boolean not null, created_by uuid not null
    );
    create table public.settlement_expenses(
      id uuid primary key default gen_random_uuid(), expense_date date, category_id uuid,
      category text, amount integer, store text, is_recurring boolean, note text,
      created_by uuid, updated_at timestamptz not null default now()
    );
    create table public.customers(id bigint primary key, name text, phone text);
    create table public.logs(
      id bigint generated by default as identity primary key, admin_id uuid, customer_id bigint,
      action text, note text, jsonb jsonb, category text, after_service_id bigint,
      updated_at timestamptz not null default now()
    );

    create table public.defective_inventory_holds(
      id uuid primary key, quantity integer, refund_line_id uuid, source_log_id bigint
    );
    create table public.customer_refund_lines(id uuid primary key, source_line_index integer);
    create table public.inventory_cost_events(
      id uuid primary key, reference_type text, reference_id text, reference_line_key text
    );
    create table public.inventory_cost_allocations(
      id uuid primary key default gen_random_uuid(), outbound_event_id uuid,
      quantity integer, unit_cost integer, created_at timestamptz not null default now()
    );
    create table public.inventory_balances(item_name text primary key, quantity integer not null);
    create table public.inventory_cost_layers(id uuid primary key default gen_random_uuid(), item_name text, remaining_quantity integer);
  `);
  await db.exec(await readFile(
    new URL("../supabase/migrations/20261007000000_add_after_service_credit_processing.sql", import.meta.url),
    "utf8",
  ));
});

after(async () => db.close());

beforeEach(async () => {
  await db.exec("begin");
  await db.query("select set_config('request.jwt.claim.sub', $1, false)", [master]);
  await db.exec(`
    insert into customers values (10, '홍길동', '010-1234-5678');
    insert into after_services(id, customer_id, item_name, quantity, service_case_type, status)
      values (1, 10, '검수용 A/S 제품', 1, 'vendor_exchange', 'sent_for_repair');
    insert into after_service_outbound_cost_allocations(after_service_id, unit_price, outbound_quantity, received_quantity)
      values (1, 4950, 1, 0);
    insert into inventory_balances values ('검수용 A/S 제품', 8);
    insert into inventory_cost_layers(item_name, remaining_quantity) values ('검수용 A/S 제품', 8);
  `);
});

afterEach(async () => db.exec("rollback"));

const inventorySnapshot = async () => ({
  balance: await q("select * from inventory_balances order by item_name"),
  layers: await q("select item_name, remaining_quantity from inventory_cost_layers order by item_name"),
  allocations: await q("select unit_price, outbound_quantity, received_quantity from after_service_outbound_cost_allocations order by id"),
});

test("적립금 처리 손실만 기록하고 재고·원가층·출고 배정은 바꾸지 않는다", async () => {
  const beforeInventory = await inventorySnapshot();

  await q("select process_after_service_credit_processing(1, '2026-10-07', 'same', null, '거래처 적립금 보상')");

  assert.deepEqual(await inventorySnapshot(), beforeInventory);
  assert.equal((await q("select status from after_services where id=1"))[0].status, "credit_processed");
  const expense = (await q("select expense_date, category, amount, store, is_recurring, note from settlement_expenses"))[0];
  assert.deepEqual(
    { ...expense, expense_date: expense.expense_date.toISOString().slice(0, 10) },
    {
      expense_date: "2026-10-07",
      category: "A/S 적립금 처리",
      amount: 4950,
      store: "common",
      is_recurring: false,
      note: "업체 불량교환 · 홍길동 · 010-1234-5678 · 검수용 A/S 제품 · 수량 1개 · 원가 4,950원 적립금처리 (손실)",
    },
  );
});

test("원가와 다름은 손실 금액만 대체하고 기존 출고 원가는 보존한다", async () => {
  const beforeInventory = await inventorySnapshot();

  await q("select process_after_service_credit_processing(1, '2026-10-07', 'different', 3200, null)");

  assert.deepEqual(await inventorySnapshot(), beforeInventory);
  assert.deepEqual(
    (await q("select original_cost, settled_cost, cost_mode from after_service_credit_settlements where after_service_id=1"))[0],
    { original_cost: 4950, settled_cost: 3200, cost_mode: "different" },
  );
  assert.equal((await q("select amount from settlement_expenses"))[0].amount, 3200);
});

test("적립금 상태를 비용 기록 없이 직접 변경하거나 마스터가 아닌 계정으로 처리할 수 없다", async () => {
  await db.exec("savepoint direct_status");
  await assert.rejects(
    db.query("update after_services set status='credit_processed' where id=1"),
    /CREDIT_PROCESSING_SETTLEMENT_REQUIRED/,
  );
  await db.exec("rollback to savepoint direct_status");
  await db.query("select set_config('request.jwt.claim.sub', $1, false)", [staff]);
  await assert.rejects(
    db.query("select process_after_service_credit_processing(1, '2026-10-07', 'same', null, null)"),
    /MASTER_REQUIRED/,
  );
});
