'use client';
import { useMemo, useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import toast from 'react-hot-toast';
import Button from '@/app/_components/Button';
import Loading from '@/app/_components/Loading';
import RichTextNoteEditor from '@/app/_components/RichTextNoteEditor';
import TaggedContent from '@/app/_components/TaggedContent';
import supabase from '@/libs/supabaseClient';
import { getComparisonDevicesWithValues } from '@/app/_domains/_comparison/_services/comparisonDeviceService';
import DeviceSearchSelect, { type DeviceSearchOption } from './DeviceSearchSelect';

type Step = { id: string; step_order: number; title: string; content: string };
export default function DeviceDefectManage() {
  const queryClient = useQueryClient(); const [deviceId, setDeviceId] = useState(''); const [title, setTitle] = useState(''); const [content, setContent] = useState(''); const [saving, setSaving] = useState(false);
  const { data: deviceData, isLoading } = useQuery({ queryKey: ['comparison', 'devices', 'defect-manage'], queryFn: getComparisonDevicesWithValues });
  const devices = deviceData?.devices ?? []; const columns = deviceData?.columns ?? []; const nameColumn = columns.find((column) => /브랜드.*기기|기기.*(명|이름)|제품.*(명|이름)/.test(column.name));
  const { data: savedDefectSteps = [] } = useQuery({ queryKey: ['comparison', 'device-defect-steps', 'saved-status'], queryFn: async () => { const { data, error } = await supabase.from('comparison_device_defect_symptom_steps').select('device_id'); if (error) throw error; return data ?? []; } });
  const savedDefectDeviceIds = useMemo(() => new Set(savedDefectSteps.map((step) => step.device_id)), [savedDefectSteps]);
  const options = useMemo<DeviceSearchOption[]>(() => devices.map((device, index) => { const values = (deviceData?.values ?? []).filter((value) => value.device_id === device.id); const label = (nameColumn && values.find((value) => value.column_id === nameColumn.id)?.value) || `기기 ${index + 1}`; return { id: device.id, label, searchText: values.map((value) => value.value).join(' '), hasSavedData: savedDefectDeviceIds.has(device.id) }; }), [deviceData?.values, devices, nameColumn, savedDefectDeviceIds]);
  const key = ['comparison', 'device-defect-steps', deviceId] as const;
  const { data: steps = [], isFetching, refetch } = useQuery({ enabled: Boolean(deviceId), queryKey: key, queryFn: async () => { const { data, error } = await supabase.from('comparison_device_defect_symptom_steps').select('id,step_order,title,content').eq('device_id', deviceId).order('step_order'); if (error) throw error; return (data ?? []) as Step[]; } });
  const refresh = async () => { await queryClient.invalidateQueries({ queryKey: key }); await queryClient.invalidateQueries({ queryKey: ['comparison', 'device-defects', deviceId] }); await queryClient.invalidateQueries({ queryKey: ['comparison', 'device-defect-steps', 'saved-status'] }); await refetch(); };
  const save = async (step: Omit<Step, 'id'> & { id?: string }) => { if (!deviceId || !step.title.trim() || !step.content.trim()) { toast.error('제목과 내용을 입력하세요.'); return false; } setSaving(true); try { const { error } = await supabase.rpc('save_comparison_device_defect_symptom_step', { p_id: step.id ?? null, p_device_id: deviceId, p_step_order: step.step_order, p_title: step.title, p_content: step.content }); if (error) throw error; await refresh(); toast.success('불량 증상을 저장했습니다.'); return true; } catch { toast.error('불량 증상을 저장하지 못했습니다.'); return false; } finally { setSaving(false); } };
  const remove = async (step: Step) => { if (!window.confirm(`${step.step_order}단계를 삭제하시겠습니까?`)) return; setSaving(true); try { const { error } = await supabase.rpc('delete_comparison_device_defect_symptom_step', { p_id: step.id }); if (error) throw error; await refresh(); toast.success('불량 증상을 삭제했습니다.'); } catch { toast.error('불량 증상을 삭제하지 못했습니다.'); } finally { setSaving(false); } };
  if (isLoading) return <Loading size="sm" text="불러오는 중..." />;
  return <div className="flex h-full min-h-0 flex-col"><h2 className="mb-1 text-lg font-semibold">기기 불량 관리</h2><p className="mb-4 text-sm text-gray-500">기기를 선택해 불량 증상 단계별 제목과 내용을 관리하세요.</p><div className="relative z-30 max-w-3xl"><DeviceSearchSelect options={options} value={deviceId} onChange={setDeviceId} /></div>{deviceId && !isFetching && <div className="mt-4 min-h-0 flex-1 space-y-4 overflow-y-auto pr-1"><section className="max-w-3xl space-y-3 rounded-xl border border-gray-200 bg-gray-50/70 p-3">{steps.map((step) => <StepCard key={step.id} step={step} disabled={saving} onSave={save} onDelete={() => remove(step)} />)}{steps.length === 0 && <p className="py-4 text-center text-sm text-gray-500">등록된 불량 증상이 없습니다.</p>}</section><section className="max-w-3xl rounded-xl border border-gray-200 bg-gray-50/70 p-3"><p className="mb-2 text-sm font-medium">불량 증상 단계 추가</p><RichTextNoteEditor value={title} onChange={setTitle} placeholder="증상 제목" compact showPreview={false} enableDividers /><div className="mt-2"><RichTextNoteEditor value={content} onChange={setContent} placeholder="증상 내용" compact showPreview={false} enableDividers /></div><Button size="sm" className="mt-2" disabled={saving} onClick={async () => { if (await save({ step_order: Math.max(0, ...steps.map((step) => step.step_order)) + 1, title, content })) { setTitle(''); setContent(''); } }}>단계 추가</Button></section></div>}</div>;
}
function StepCard({ step, disabled, onSave, onDelete }: { step: Step; disabled: boolean; onSave: (step: Step) => Promise<boolean>; onDelete: () => void }) { const [draft, setDraft] = useState(step); const [editing, setEditing] = useState(false); if (!editing) return <article className="rounded-xl border border-gray-300 bg-white p-4"><span className="text-xs font-semibold text-brand-600">{step.step_order}단계</span><h3 className="mt-1 text-base font-semibold text-gray-950"><TaggedContent inline content={step.title} /></h3><div className="mt-2 text-sm leading-relaxed text-gray-900"><TaggedContent content={step.content} /></div><div className="mt-3 flex justify-end gap-2"><Button size="xs" disabled={disabled} onClick={() => setEditing(true)}>수정</Button><Button size="xs" variant="danger" disabled={disabled} onClick={onDelete}>삭제</Button></div></article>; return <article className="rounded-xl border border-gray-300 bg-white p-4"><p className="mb-1 text-xs font-medium text-gray-500">제목</p><RichTextNoteEditor value={draft.title} onChange={(title) => setDraft((current) => ({ ...current, title }))} compact showPreview={false} enableDividers /><p className="mb-1 mt-3 text-xs font-medium text-gray-500">내용</p><RichTextNoteEditor value={draft.content} onChange={(content) => setDraft((current) => ({ ...current, content }))} compact showPreview={false} enableDividers /><div className="mt-2 flex justify-end gap-2"><Button size="xs" disabled={disabled} onClick={async () => { if (await onSave(draft)) setEditing(false); }}>저장</Button><Button size="xs" variant="gray" disabled={disabled} onClick={() => { setDraft(step); setEditing(false); }}>취소</Button><Button size="xs" variant="danger" disabled={disabled} onClick={onDelete}>삭제</Button></div></article>; }
