select '젤로 투명케이스' item,
(select jsonb_agg(jsonb_build_object('id',l.id,'q',l.original_quantity,'remaining',l.remaining_quantity,'price',l.unit_cost,'queue',l.queue_sequence,'at',e.event_at,'type',e.event_type) order by l.queue_sequence,e.event_at,l.id) from inventory_cost_layers l join inventory_cost_events e on e.id=l.source_event_id where l.item_name='젤로 투명케이스' and e.event_at>='2026-07-22 00:00:00+09') layers,
(select jsonb_agg(jsonb_build_object('id',e.id,'ref',e.reference_id,'key',e.reference_line_key,'at',e.event_at,'q',e.quantity,'type',e.event_type,'alloc',(select jsonb_agg(jsonb_build_object('id',a.id,'layer',a.source_layer_id,'q',a.quantity,'price',a.unit_cost)) from inventory_cost_allocations a where a.outbound_event_id=e.id)) order by e.event_at,e.id) from inventory_cost_events e where e.item_name='젤로 투명케이스' and e.direction='out' and e.metadata->>'restoredAt' is null and e.event_at>='2026-07-22 00:00:00+09') outs,
(select jsonb_agg(jsonb_build_object('id',l.id,'line',i.idx,'at',l.created_at,'q',(i.v->>'quantity')::int) order by l.created_at,l.id,i.idx) from logs l cross join lateral jsonb_array_elements(l.jsonb->'items') with ordinality i(v,idx) where l.category='stamp' and i.v->>'itemName'='젤로 투명케이스' and i.v->>'remark' ~ '^서비스($|[,\s(])' and l.created_at>='2026-07-22 00:00:00+09') services,
(select jsonb_agg(to_jsonb(s)) from inventory_service_cost_links s join inventory_cost_allocations a on a.id=s.allocation_id join inventory_cost_layers x on x.id=a.source_layer_id where x.item_name='젤로 투명케이스') links
union all
select '말론S 0.6 팟' item,
(select jsonb_agg(jsonb_build_object('id',l.id,'q',l.original_quantity,'remaining',l.remaining_quantity,'price',l.unit_cost,'queue',l.queue_sequence,'at',e.event_at,'type',e.event_type) order by l.queue_sequence,e.event_at,l.id) from inventory_cost_layers l join inventory_cost_events e on e.id=l.source_event_id where l.item_name='말론S 0.6 팟' and e.event_at>='2026-07-22 00:00:00+09') layers,
(select jsonb_agg(jsonb_build_object('id',e.id,'ref',e.reference_id,'key',e.reference_line_key,'at',e.event_at,'q',e.quantity,'type',e.event_type,'alloc',(select jsonb_agg(jsonb_build_object('id',a.id,'layer',a.source_layer_id,'q',a.quantity,'price',a.unit_cost)) from inventory_cost_allocations a where a.outbound_event_id=e.id)) order by e.event_at,e.id) from inventory_cost_events e where e.item_name='말론S 0.6 팟' and e.direction='out' and e.metadata->>'restoredAt' is null and e.event_at>='2026-07-22 00:00:00+09') outs,
(select jsonb_agg(jsonb_build_object('id',l.id,'line',i.idx,'at',l.created_at,'q',(i.v->>'quantity')::int) order by l.created_at,l.id,i.idx) from logs l cross join lateral jsonb_array_elements(l.jsonb->'items') with ordinality i(v,idx) where l.category='stamp' and i.v->>'itemName'='말론S 0.6 팟' and i.v->>'remark' ~ '^서비스($|[,\s(])' and l.created_at>='2026-07-22 00:00:00+09') services,
(select jsonb_agg(to_jsonb(s)) from inventory_service_cost_links s join inventory_cost_allocations a on a.id=s.allocation_id join inventory_cost_layers x on x.id=a.source_layer_id where x.item_name='말론S 0.6 팟') links
union all
select '말론S 투명케이스' item,
(select jsonb_agg(jsonb_build_object('id',l.id,'q',l.original_quantity,'remaining',l.remaining_quantity,'price',l.unit_cost,'queue',l.queue_sequence,'at',e.event_at,'type',e.event_type) order by l.queue_sequence,e.event_at,l.id) from inventory_cost_layers l join inventory_cost_events e on e.id=l.source_event_id where l.item_name='말론S 투명케이스' and e.event_at>='2026-07-22 00:00:00+09') layers,
(select jsonb_agg(jsonb_build_object('id',e.id,'ref',e.reference_id,'key',e.reference_line_key,'at',e.event_at,'q',e.quantity,'type',e.event_type,'alloc',(select jsonb_agg(jsonb_build_object('id',a.id,'layer',a.source_layer_id,'q',a.quantity,'price',a.unit_cost)) from inventory_cost_allocations a where a.outbound_event_id=e.id)) order by e.event_at,e.id) from inventory_cost_events e where e.item_name='말론S 투명케이스' and e.direction='out' and e.metadata->>'restoredAt' is null and e.event_at>='2026-07-22 00:00:00+09') outs,
(select jsonb_agg(jsonb_build_object('id',l.id,'line',i.idx,'at',l.created_at,'q',(i.v->>'quantity')::int) order by l.created_at,l.id,i.idx) from logs l cross join lateral jsonb_array_elements(l.jsonb->'items') with ordinality i(v,idx) where l.category='stamp' and i.v->>'itemName'='말론S 투명케이스' and i.v->>'remark' ~ '^서비스($|[,\s(])' and l.created_at>='2026-07-22 00:00:00+09') services,
(select jsonb_agg(to_jsonb(s)) from inventory_service_cost_links s join inventory_cost_allocations a on a.id=s.allocation_id join inventory_cost_layers x on x.id=a.source_layer_id where x.item_name='말론S 투명케이스') links
union all
select '디오X 투명케이스' item,
(select jsonb_agg(jsonb_build_object('id',l.id,'q',l.original_quantity,'remaining',l.remaining_quantity,'price',l.unit_cost,'queue',l.queue_sequence,'at',e.event_at,'type',e.event_type) order by l.queue_sequence,e.event_at,l.id) from inventory_cost_layers l join inventory_cost_events e on e.id=l.source_event_id where l.item_name='디오X 투명케이스' and e.event_at>='2026-07-22 00:00:00+09') layers,
(select jsonb_agg(jsonb_build_object('id',e.id,'ref',e.reference_id,'key',e.reference_line_key,'at',e.event_at,'q',e.quantity,'type',e.event_type,'alloc',(select jsonb_agg(jsonb_build_object('id',a.id,'layer',a.source_layer_id,'q',a.quantity,'price',a.unit_cost)) from inventory_cost_allocations a where a.outbound_event_id=e.id)) order by e.event_at,e.id) from inventory_cost_events e where e.item_name='디오X 투명케이스' and e.direction='out' and e.metadata->>'restoredAt' is null and e.event_at>='2026-07-22 00:00:00+09') outs,
(select jsonb_agg(jsonb_build_object('id',l.id,'line',i.idx,'at',l.created_at,'q',(i.v->>'quantity')::int) order by l.created_at,l.id,i.idx) from logs l cross join lateral jsonb_array_elements(l.jsonb->'items') with ordinality i(v,idx) where l.category='stamp' and i.v->>'itemName'='디오X 투명케이스' and i.v->>'remark' ~ '^서비스($|[,\s(])' and l.created_at>='2026-07-22 00:00:00+09') services,
(select jsonb_agg(to_jsonb(s)) from inventory_service_cost_links s join inventory_cost_allocations a on a.id=s.allocation_id join inventory_cost_layers x on x.id=a.source_layer_id where x.item_name='디오X 투명케이스') links
union all
select '젤로 0.8 부스트팟' item,
(select jsonb_agg(jsonb_build_object('id',l.id,'q',l.original_quantity,'remaining',l.remaining_quantity,'price',l.unit_cost,'queue',l.queue_sequence,'at',e.event_at,'type',e.event_type) order by l.queue_sequence,e.event_at,l.id) from inventory_cost_layers l join inventory_cost_events e on e.id=l.source_event_id where l.item_name='젤로 0.8 부스트팟' and e.event_at>='2026-07-22 00:00:00+09') layers,
(select jsonb_agg(jsonb_build_object('id',e.id,'ref',e.reference_id,'key',e.reference_line_key,'at',e.event_at,'q',e.quantity,'type',e.event_type,'alloc',(select jsonb_agg(jsonb_build_object('id',a.id,'layer',a.source_layer_id,'q',a.quantity,'price',a.unit_cost)) from inventory_cost_allocations a where a.outbound_event_id=e.id)) order by e.event_at,e.id) from inventory_cost_events e where e.item_name='젤로 0.8 부스트팟' and e.direction='out' and e.metadata->>'restoredAt' is null and e.event_at>='2026-07-22 00:00:00+09') outs,
(select jsonb_agg(jsonb_build_object('id',l.id,'line',i.idx,'at',l.created_at,'q',(i.v->>'quantity')::int) order by l.created_at,l.id,i.idx) from logs l cross join lateral jsonb_array_elements(l.jsonb->'items') with ordinality i(v,idx) where l.category='stamp' and i.v->>'itemName'='젤로 0.8 부스트팟' and i.v->>'remark' ~ '^서비스($|[,\s(])' and l.created_at>='2026-07-22 00:00:00+09') services,
(select jsonb_agg(to_jsonb(s)) from inventory_service_cost_links s join inventory_cost_allocations a on a.id=s.allocation_id join inventory_cost_layers x on x.id=a.source_layer_id where x.item_name='젤로 0.8 부스트팟') links
union all
select '아보카도 aio 0.6 팟' item,
(select jsonb_agg(jsonb_build_object('id',l.id,'q',l.original_quantity,'remaining',l.remaining_quantity,'price',l.unit_cost,'queue',l.queue_sequence,'at',e.event_at,'type',e.event_type) order by l.queue_sequence,e.event_at,l.id) from inventory_cost_layers l join inventory_cost_events e on e.id=l.source_event_id where l.item_name='아보카도 aio 0.6 팟' and e.event_at>='2026-07-22 00:00:00+09') layers,
(select jsonb_agg(jsonb_build_object('id',e.id,'ref',e.reference_id,'key',e.reference_line_key,'at',e.event_at,'q',e.quantity,'type',e.event_type,'alloc',(select jsonb_agg(jsonb_build_object('id',a.id,'layer',a.source_layer_id,'q',a.quantity,'price',a.unit_cost)) from inventory_cost_allocations a where a.outbound_event_id=e.id)) order by e.event_at,e.id) from inventory_cost_events e where e.item_name='아보카도 aio 0.6 팟' and e.direction='out' and e.metadata->>'restoredAt' is null and e.event_at>='2026-07-22 00:00:00+09') outs,
(select jsonb_agg(jsonb_build_object('id',l.id,'line',i.idx,'at',l.created_at,'q',(i.v->>'quantity')::int) order by l.created_at,l.id,i.idx) from logs l cross join lateral jsonb_array_elements(l.jsonb->'items') with ordinality i(v,idx) where l.category='stamp' and i.v->>'itemName'='아보카도 aio 0.6 팟' and i.v->>'remark' ~ '^서비스($|[,\s(])' and l.created_at>='2026-07-22 00:00:00+09') services,
(select jsonb_agg(to_jsonb(s)) from inventory_service_cost_links s join inventory_cost_allocations a on a.id=s.allocation_id join inventory_cost_layers x on x.id=a.source_layer_id where x.item_name='아보카도 aio 0.6 팟') links
union all
select '발라리안맥스프로 투명케이스 신형' item,
(select jsonb_agg(jsonb_build_object('id',l.id,'q',l.original_quantity,'remaining',l.remaining_quantity,'price',l.unit_cost,'queue',l.queue_sequence,'at',e.event_at,'type',e.event_type) order by l.queue_sequence,e.event_at,l.id) from inventory_cost_layers l join inventory_cost_events e on e.id=l.source_event_id where l.item_name='발라리안맥스프로 투명케이스 신형' and e.event_at>='2026-07-22 00:00:00+09') layers,
(select jsonb_agg(jsonb_build_object('id',e.id,'ref',e.reference_id,'key',e.reference_line_key,'at',e.event_at,'q',e.quantity,'type',e.event_type,'alloc',(select jsonb_agg(jsonb_build_object('id',a.id,'layer',a.source_layer_id,'q',a.quantity,'price',a.unit_cost)) from inventory_cost_allocations a where a.outbound_event_id=e.id)) order by e.event_at,e.id) from inventory_cost_events e where e.item_name='발라리안맥스프로 투명케이스 신형' and e.direction='out' and e.metadata->>'restoredAt' is null and e.event_at>='2026-07-22 00:00:00+09') outs,
(select jsonb_agg(jsonb_build_object('id',l.id,'line',i.idx,'at',l.created_at,'q',(i.v->>'quantity')::int) order by l.created_at,l.id,i.idx) from logs l cross join lateral jsonb_array_elements(l.jsonb->'items') with ordinality i(v,idx) where l.category='stamp' and i.v->>'itemName'='발라리안맥스프로 투명케이스 신형' and i.v->>'remark' ~ '^서비스($|[,\s(])' and l.created_at>='2026-07-22 00:00:00+09') services,
(select jsonb_agg(to_jsonb(s)) from inventory_service_cost_links s join inventory_cost_allocations a on a.id=s.allocation_id join inventory_cost_layers x on x.id=a.source_layer_id where x.item_name='발라리안맥스프로 투명케이스 신형') links
union all
select '하복 공팟 클리어' item,
(select jsonb_agg(jsonb_build_object('id',l.id,'q',l.original_quantity,'remaining',l.remaining_quantity,'price',l.unit_cost,'queue',l.queue_sequence,'at',e.event_at,'type',e.event_type) order by l.queue_sequence,e.event_at,l.id) from inventory_cost_layers l join inventory_cost_events e on e.id=l.source_event_id where l.item_name='하복 공팟 클리어' and e.event_at>='2026-07-22 00:00:00+09') layers,
(select jsonb_agg(jsonb_build_object('id',e.id,'ref',e.reference_id,'key',e.reference_line_key,'at',e.event_at,'q',e.quantity,'type',e.event_type,'alloc',(select jsonb_agg(jsonb_build_object('id',a.id,'layer',a.source_layer_id,'q',a.quantity,'price',a.unit_cost)) from inventory_cost_allocations a where a.outbound_event_id=e.id)) order by e.event_at,e.id) from inventory_cost_events e where e.item_name='하복 공팟 클리어' and e.direction='out' and e.metadata->>'restoredAt' is null and e.event_at>='2026-07-22 00:00:00+09') outs,
(select jsonb_agg(jsonb_build_object('id',l.id,'line',i.idx,'at',l.created_at,'q',(i.v->>'quantity')::int) order by l.created_at,l.id,i.idx) from logs l cross join lateral jsonb_array_elements(l.jsonb->'items') with ordinality i(v,idx) where l.category='stamp' and i.v->>'itemName'='하복 공팟 클리어' and i.v->>'remark' ~ '^서비스($|[,\s(])' and l.created_at>='2026-07-22 00:00:00+09') services,
(select jsonb_agg(to_jsonb(s)) from inventory_service_cost_links s join inventory_cost_allocations a on a.id=s.allocation_id join inventory_cost_layers x on x.id=a.source_layer_id where x.item_name='하복 공팟 클리어') links
union all
select '하복 0.6 코일' item,
(select jsonb_agg(jsonb_build_object('id',l.id,'q',l.original_quantity,'remaining',l.remaining_quantity,'price',l.unit_cost,'queue',l.queue_sequence,'at',e.event_at,'type',e.event_type) order by l.queue_sequence,e.event_at,l.id) from inventory_cost_layers l join inventory_cost_events e on e.id=l.source_event_id where l.item_name='하복 0.6 코일' and e.event_at>='2026-07-22 00:00:00+09') layers,
(select jsonb_agg(jsonb_build_object('id',e.id,'ref',e.reference_id,'key',e.reference_line_key,'at',e.event_at,'q',e.quantity,'type',e.event_type,'alloc',(select jsonb_agg(jsonb_build_object('id',a.id,'layer',a.source_layer_id,'q',a.quantity,'price',a.unit_cost)) from inventory_cost_allocations a where a.outbound_event_id=e.id)) order by e.event_at,e.id) from inventory_cost_events e where e.item_name='하복 0.6 코일' and e.direction='out' and e.metadata->>'restoredAt' is null and e.event_at>='2026-07-22 00:00:00+09') outs,
(select jsonb_agg(jsonb_build_object('id',l.id,'line',i.idx,'at',l.created_at,'q',(i.v->>'quantity')::int) order by l.created_at,l.id,i.idx) from logs l cross join lateral jsonb_array_elements(l.jsonb->'items') with ordinality i(v,idx) where l.category='stamp' and i.v->>'itemName'='하복 0.6 코일' and i.v->>'remark' ~ '^서비스($|[,\s(])' and l.created_at>='2026-07-22 00:00:00+09') services,
(select jsonb_agg(to_jsonb(s)) from inventory_service_cost_links s join inventory_cost_allocations a on a.id=s.allocation_id join inventory_cost_layers x on x.id=a.source_layer_id where x.item_name='하복 0.6 코일') links
union all
select '하부코일 1.6' item,
(select jsonb_agg(jsonb_build_object('id',l.id,'q',l.original_quantity,'remaining',l.remaining_quantity,'price',l.unit_cost,'queue',l.queue_sequence,'at',e.event_at,'type',e.event_type) order by l.queue_sequence,e.event_at,l.id) from inventory_cost_layers l join inventory_cost_events e on e.id=l.source_event_id where l.item_name='하부코일 1.6' and e.event_at>='2026-07-22 00:00:00+09') layers,
(select jsonb_agg(jsonb_build_object('id',e.id,'ref',e.reference_id,'key',e.reference_line_key,'at',e.event_at,'q',e.quantity,'type',e.event_type,'alloc',(select jsonb_agg(jsonb_build_object('id',a.id,'layer',a.source_layer_id,'q',a.quantity,'price',a.unit_cost)) from inventory_cost_allocations a where a.outbound_event_id=e.id)) order by e.event_at,e.id) from inventory_cost_events e where e.item_name='하부코일 1.6' and e.direction='out' and e.metadata->>'restoredAt' is null and e.event_at>='2026-07-22 00:00:00+09') outs,
(select jsonb_agg(jsonb_build_object('id',l.id,'line',i.idx,'at',l.created_at,'q',(i.v->>'quantity')::int) order by l.created_at,l.id,i.idx) from logs l cross join lateral jsonb_array_elements(l.jsonb->'items') with ordinality i(v,idx) where l.category='stamp' and i.v->>'itemName'='하부코일 1.6' and i.v->>'remark' ~ '^서비스($|[,\s(])' and l.created_at>='2026-07-22 00:00:00+09') services,
(select jsonb_agg(to_jsonb(s)) from inventory_service_cost_links s join inventory_cost_allocations a on a.id=s.allocation_id join inventory_cost_layers x on x.id=a.source_layer_id where x.item_name='하부코일 1.6') links
union all
select '젤로맥스 투명케이스' item,
(select jsonb_agg(jsonb_build_object('id',l.id,'q',l.original_quantity,'remaining',l.remaining_quantity,'price',l.unit_cost,'queue',l.queue_sequence,'at',e.event_at,'type',e.event_type) order by l.queue_sequence,e.event_at,l.id) from inventory_cost_layers l join inventory_cost_events e on e.id=l.source_event_id where l.item_name='젤로맥스 투명케이스' and e.event_at>='2026-07-22 00:00:00+09') layers,
(select jsonb_agg(jsonb_build_object('id',e.id,'ref',e.reference_id,'key',e.reference_line_key,'at',e.event_at,'q',e.quantity,'type',e.event_type,'alloc',(select jsonb_agg(jsonb_build_object('id',a.id,'layer',a.source_layer_id,'q',a.quantity,'price',a.unit_cost)) from inventory_cost_allocations a where a.outbound_event_id=e.id)) order by e.event_at,e.id) from inventory_cost_events e where e.item_name='젤로맥스 투명케이스' and e.direction='out' and e.metadata->>'restoredAt' is null and e.event_at>='2026-07-22 00:00:00+09') outs,
(select jsonb_agg(jsonb_build_object('id',l.id,'line',i.idx,'at',l.created_at,'q',(i.v->>'quantity')::int) order by l.created_at,l.id,i.idx) from logs l cross join lateral jsonb_array_elements(l.jsonb->'items') with ordinality i(v,idx) where l.category='stamp' and i.v->>'itemName'='젤로맥스 투명케이스' and i.v->>'remark' ~ '^서비스($|[,\s(])' and l.created_at>='2026-07-22 00:00:00+09') services,
(select jsonb_agg(to_jsonb(s)) from inventory_service_cost_links s join inventory_cost_allocations a on a.id=s.allocation_id join inventory_cost_layers x on x.id=a.source_layer_id where x.item_name='젤로맥스 투명케이스') links;
