-- 출고 이력 품목 선택 시 표시할 메모 안내 규칙입니다.
create table if not exists public.outbound_memo_rules (
  id bigint generated by default as identity primary key,
  target_type text not null check (target_type in ('category', 'item')),
  category_id bigint references public.item_categories(id) on delete cascade,
  item_id bigint references public.items(id) on delete cascade,
  message text not null check (length(trim(message)) > 0),
  placeholder_message text,
  auto_select_memo boolean not null default true,
  applicable_outbound_types text[] not null default array[
    'standard', 'service', 'exchange_in', 'exchange_out', 'price_adjust'
  ]::text[],
  is_required boolean not null default false,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint outbound_memo_rules_target_check check (
    (target_type = 'category' and category_id is not null and item_id is null)
    or
    (target_type = 'item' and item_id is not null and category_id is null)
  )
);

-- 이미 테이블을 만든 환경에도 출고 유형 설정을 추가합니다.
alter table public.outbound_memo_rules
  add column if not exists applicable_outbound_types text[] not null default array[
    'standard', 'service', 'exchange_in', 'exchange_out', 'price_adjust'
  ]::text[];

-- 안내 문구와 입력창 예시를 서로 다르게 설정할 수 있습니다.
alter table public.outbound_memo_rules
  add column if not exists placeholder_message text;

create unique index if not exists outbound_memo_rules_category_unique
  on public.outbound_memo_rules (category_id)
  where target_type = 'category';

create unique index if not exists outbound_memo_rules_item_unique
  on public.outbound_memo_rules (item_id)
  where target_type = 'item';

-- 기존 코드에 있던 기기 안내를 최초 기본 규칙으로 이전합니다.
insert into public.outbound_memo_rules (
  target_type,
  category_id,
  message,
  auto_select_memo,
  is_required
)
select
  'category',
  id,
  '박스 매장 보관 유무를 적어주세요.',
  true,
  false
from public.item_categories
where trim(name) = '기기'
on conflict do nothing;

alter table public.outbound_memo_rules enable row level security;

drop policy if exists "authenticated users can read outbound memo rules"
  on public.outbound_memo_rules;
create policy "authenticated users can read outbound memo rules"
  on public.outbound_memo_rules for select
  to authenticated using (true);

drop policy if exists "admins can manage outbound memo rules"
  on public.outbound_memo_rules;
create policy "admins can manage outbound memo rules"
  on public.outbound_memo_rules for all
  to authenticated
  using (
    exists (
      select 1 from public.users
      where users.id = auth.uid() and users.oss_role = 'admin'
    )
  )
  with check (
    exists (
      select 1 from public.users
      where users.id = auth.uid() and users.oss_role = 'admin'
    )
  );
