create table public.comparison_customer_required_guide_steps (id uuid primary key default gen_random_uuid(), step_order integer not null unique, title text not null, content text not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.comparison_customer_required_guide_notes (id uuid primary key default gen_random_uuid(), device_id uuid not null references public.comparison_devices(id) on delete cascade, step_id uuid not null references public.comparison_customer_required_guide_steps(id) on delete cascade, content text not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(device_id, step_id));
alter table public.comparison_customer_required_guide_steps enable row level security;
alter table public.comparison_customer_required_guide_notes enable row level security;
create policy "authenticated reads customer required guide steps" on public.comparison_customer_required_guide_steps for select to authenticated using (true);
create policy "authenticated reads customer required guide notes" on public.comparison_customer_required_guide_notes for select to authenticated using (true);
insert into public.comparison_columns(name,key,sort_order,is_active) select '고객 필수 안내','customer_required_guide',coalesce((select max(sort_order)+1 from public.comparison_columns),0),true where not exists (select 1 from public.comparison_columns where key='customer_required_guide');

create function public.save_comparison_customer_required_guide_step(p_id uuid, p_step_order integer, p_title text, p_content text) returns public.comparison_customer_required_guide_steps language plpgsql security definer set search_path=public as $$ declare v public.comparison_customer_required_guide_steps; begin if not exists(select 1 from public.users where id=auth.uid() and oss_role in ('admin','master')) then raise exception 'ADMIN_REQUIRED'; end if; if p_id is null then insert into public.comparison_customer_required_guide_steps(step_order,title,content) values(p_step_order,btrim(p_title),btrim(p_content)) returning * into v; else update public.comparison_customer_required_guide_steps set step_order=p_step_order,title=btrim(p_title),content=btrim(p_content),updated_at=now() where id=p_id returning * into v; end if; return v; end; $$;
create function public.save_comparison_customer_required_guide_note(p_device_id uuid, p_step_id uuid, p_content text) returns public.comparison_customer_required_guide_notes language plpgsql security definer set search_path=public as $$ declare v public.comparison_customer_required_guide_notes; begin if not exists(select 1 from public.users where id=auth.uid() and oss_role in ('admin','master')) then raise exception 'ADMIN_REQUIRED'; end if; insert into public.comparison_customer_required_guide_notes(device_id,step_id,content) values(p_device_id,p_step_id,btrim(p_content)) on conflict(device_id,step_id) do update set content=excluded.content,updated_at=now() returning * into v; return v; end; $$;
create function public.delete_comparison_customer_required_guide_step(p_id uuid) returns void language plpgsql security definer set search_path=public as $$ begin if not exists(select 1 from public.users where id=auth.uid() and oss_role in ('admin','master')) then raise exception 'ADMIN_REQUIRED'; end if; delete from public.comparison_customer_required_guide_steps where id=p_id; end; $$;
revoke all on function public.save_comparison_customer_required_guide_step(uuid,integer,text,text) from public,anon;
revoke all on function public.save_comparison_customer_required_guide_note(uuid,uuid,text) from public,anon;
revoke all on function public.delete_comparison_customer_required_guide_step(uuid) from public,anon;
grant execute on function public.save_comparison_customer_required_guide_step(uuid,integer,text,text) to authenticated;
grant execute on function public.save_comparison_customer_required_guide_note(uuid,uuid,text) to authenticated;
grant execute on function public.delete_comparison_customer_required_guide_step(uuid) to authenticated;
